Version 1.0
sadrasabouri/pyrandwalk pull request #7
Opened 2021-06-03 06:13 UTC by sadrasabouri

#### Reference Issues/PRs
This PR will close #1 and close #3.
This version contains:
```
### Added
- codefactor tests
- pypi installing guid
- `Document.ipynb`
- `Examples.ipynb`
- `notebook_check.py`
- `precision` added to `is_prob_dist`
- `payoff` attribute
- `cost` attribute
- `discount` attribute
- `best_policy` method
### Changes
- `make_prob_dist` bug fixed
- `final_dist` bug fixed
```

2021-06-03 06:29 UTC, sepandhaghighi commented
@sadrasabouri Nice 💯 
I will review this PR ASAP

2021-06-03 12:05 UTC, sepandhaghighi requested changes

2021-06-03 12:05 UTC, sepandhaghighi commented on README.md
Correct format:
<blockquote>1- Lawler, Gregory F. Introduction to stochastic processes. Chapman and Hall/CRC, 2018.</blockquote>
<blockquote>2- <a href="https://markusfeng.com/projects/graph/">Markusfeng</a></blockquote>

2021-06-03 12:31 UTC, sepandhaghighi requested changes

2021-06-03 12:31 UTC, sepandhaghighi commented on CHANGELOG.md
> +[Unreleased]: https://github.com/sadrasabouri/pyrandwalk/compare/v1.0...dev
What? PyCM?!?

Correct:
```
[Unreleased]: https://github.com/sadrasabouri/pyrandwalk/compare/v1.0...dev
[1.0]: https://github.com/sadrasabouri/pyrandwalk/compare/v0.09...v1.0
[0.09]: https://github.com/sadrasabouri/pyrandwalk/compare/9113e4c...v0.09
```

2021-06-03 12:46 UTC, sadrasabouri commented on CHANGELOG.md
> +[Unreleased]: https://github.com/sadrasabouri/pyrandwalk/compare/v1.0...dev
Oh :+1: 
Copy paste problems :smile:.

2021-06-05 12:22 UTC, sepandhaghighi requested changes
Please take a look at `CONTRIBUTING.md`.
```
To add a new class statistic visit here
To add a new overall statistic visit here
To add a new interpretation visit here
```

2021-06-07 06:34 UTC, sadrasabouri commented
> Please take a look at `CONTRIBUTING.md`.
> 
> ```
> To add a new class statistic visit here
> To add a new overall statistic visit here
> To add a new interpretation visit here
> ```

Aha. Same copy paste problem.

2021-06-07 22:50 UTC, sepandhaghighi requested changes

2021-06-07 22:50 UTC, sepandhaghighi commented on CHANGELOG.md
> +- `precision` added to `is_prob_dist`
`precision` (parameter?) added to `is_prob_dist` (function?)

2021-06-07 22:50 UTC, sepandhaghighi commented on Document/Document.ipynb
> +    "!pip install pyrandwalk\n",
Run `!pip -q -q install pyrandwalk` to bypass the installation messages

2021-06-07 22:50 UTC, sepandhaghighi commented on Document/Examples.ipynb
> +    "!pip install pyrandwalk\n",
Run `!pip -q -q install pyrandwalk` to bypass the installation messages

2021-06-08 19:41 UTC, sepandhaghighi approved these changes

2021-06-08 19:43 UTC, sepandhaghighi commented
@sadrasabouri LGTM 🥇

2021-06-09 05:14 UTC, merged